name: GUIHelper
main: me.gabytm.minecraft.guihelper.GUIHelper
description: The ultimate solution for creating professional GUIs
version: ${version}

api-version: '1.13'
author: GabyTM
website: https://gabytm.me/

softdepend:
  - HeadDatabase
  # Custom items
  - ItemsAdder
  - Oraxen

permissions:
  guihelper.use:
    description: The permission required to access GUI Helper commands
    default: op